<?php $this->headTitle('Leave Management'); ?>

<div class="content-header">
    <h1>
      Leave Management
      <small>LIST OF COURSES OFFERED</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->url('home'); ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Leave Management</li>
    </ol>
</div>
<section class="content">
    <div class="row-fluid">
        <div id="accordion">
            <h1>
                <span class="pull-right">ADD</span>
            </h1>
            <div>
              <div id="tabs">
                <ul>
                  <li><a href="#tabs-1">Tesda Course</a></li>                  
                </ul>
                <div id="tabs-1">
                  <p>Phasellus ipsum. Nunc tristique tempus lectus.</p>
                </div>                           
              </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="box">
        <div class="box-header">
          <h3 class="box-title">Data Table With Full Features</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>Course Code</th>
              <th>Descriptive Title</th>
              <th>Description</th>
              <th>Total Hours</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td>Trident</td>
              <td>Internet
                Explorer 4.0
              </td>
              <td>Win 95+</td>
              <td> 4</td>
              <td>X</td>
            </tr>
            <tr>
              <td>Trident</td>
              <td>Internet
                Explorer 5.0
              </td>
              <td>Win 95+</td>
              <td>5</td>
              <td>C</td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
              <th>Rendering engine</th>
              <th>Browser</th>
              <th>Platform(s)</th>
              <th>Engine version</th>
              <th>CSS grade</th>
            </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
</section>

<?php

$this->inlineScript()->captureStart();
echo <<<JS
    $(function() {
        $( "#accordion" ).accordion({
            collapsible: true,
            active: false
        });
    });

    $(function() {
        $( "#tabs" ).tabs();
    });      
JS;
$this->inlineScript()->captureEnd();
?>